[wip] Document instanced pipelines
concourse/docs pull request #401
Opened 2021-01-26 22:50 UTC by aoldershaw

2021-01-29 16:38 UTC, aoldershaw commented
@vito by the way, yesterday I mentioned that the term "instance groups" is just an invented name that's used in the codebase, but that's not entirely true - with concourse/concourse#6433, the search bar got a new `group:` filter that allows you to both filter by the shared name of instanced pipelines (or the instance group name)

The difference between the `group:` filter and just regular search by pipeline name is that in addition to filtering by name, when a `group:` filter is applied, the dashboard drills into instance groups (or expands the instance groups) to view the individual instanced pipeline cards (in fact, clicking an instance group is just a shorthand for applying a `team:` and `group:` filter, i.e. expand just this one instance group)

2021-01-29 18:07 UTC, vito commented
@aoldershaw Gotcha, makes sense. I think there are just a couple things about the name that throw me off, but I couldn't quite pinpoint it yet when we were chatting.

The main thing that gives me pause about the term 'instance groups' is that it raises the question as to what an 'instance' is. I wonder if 'pipeline groups' would be clearer? Or maybe we could just spell it out as 'pipeline instance groups'?

One concern is that we already have something that could be called 'pipeline groups', i.e. [`groups:`](https://concourse-ci.org/pipelines.html#schema.pipeline.groups). So maybe that's not a good idea. Maybe 'pipeline sets,' but that could be confusing with `set-pipeline`. 😆 There's 'pipeline matrix', but no one wants to deal with the plural form, and it's a bit overloaded (I don't really think of our set of release pipelines as a 'matrix' for some reason).

We could go full circle and say 'pipeline spaces', but that might make it sound like a loftier abstraction than it really is. (e.g. namespacing)

I think this is kind of an oversight with the RFC - it says how to define each instance, but it doesn't provide a mental model or useful terminology for the resulting set of them which are associated by name.

Just thinking out loud at this point - seems like this is pretty prominent UX that we may want to suss out and make sure we're representing everything as clearly as possible before we remove the 'experimental' label.

(/cc @matthewpereira)

2021-02-03 16:56 UTC, vito requested changes
Just a few tweaks, I think we can get this out with v7.0 so long as we land on a stable URL for it.

2021-02-03 16:56 UTC, vito commented on lit/docs/pipelines/instance-groups.lit
> +\title{Grouping Pipelines}{instance-groups}
While we work out a good name for this, can we have a stable tag like `pipeline-instances` or `instanced-pipelines`? That way we can at least start linking to it without breaking the URL later.

2021-02-03 19:37 UTC, aoldershaw commented on lit/docs/jobs/steps.lit
> +        the pipeline's identity
Changed to `identifier` which feels a little more concrete than `identity`

2021-02-03 20:08 UTC, vito approved these changes
lgtm!

2021-02-03 20:16 UTC, merged